# Generated by Django 6.0.1 on 2026-02-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_update_logistics_status_and_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticianprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Новый'), ('in_progress', 'Собирается'), ('confirmed', 'Собран'), ('shipped', 'Передан в доставку'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
