# Generated by Django 6.0.1 on 2026-02-12 20:17

from django.db import migrations, models


def migrate_courier_status(apps, schema_editor):
    Courier = apps.get_model("crm", "Courier")
    Courier.objects.filter(status="offline").update(status="on_route")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_logisticianprofile_id_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(migrate_courier_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name='courier',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая широта (альт)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая долгота (альт)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. объём (м³)'),
        ),
        migrations.AddField(
            model_name='courier',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. вес (кг)'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В пути'), ('done', 'Завершена')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят'), ('on_route', 'В рейсе')], default='free', max_length=20, verbose_name='Статус'),
        ),
    ]
