# Generated by Django 6.0.1 on 2026-02-12 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_logistics_statuses(apps, schema_editor):
    Courier = apps.get_model("crm", "Courier")
    Delivery = apps.get_model("crm", "Delivery")
    Route = apps.get_model("crm", "Route")
    RouteStop = apps.get_model("crm", "RouteStop")

    courier_map = {
        "free": "Свободен",
        "busy": "Занят",
        "on_route": "В рейсе",
        "Свободен": "Свободен",
        "Занят": "Занят",
        "В рейсе": "В рейсе",
    }
    for old, new in courier_map.items():
        Courier.objects.filter(status=old).update(status=new)

    delivery_map = {
        "unassigned": "Не назначено",
        "planned": "Запланировано",
        "on_route": "В пути",
        "delivered": "Доставлено",
        "cancelled": "Отменено",
        "Не назначено": "Не назначено",
        "Запланировано": "Запланировано",
        "В пути": "В пути",
        "Доставлено": "Доставлено",
        "Отменено": "Отменено",
    }
    for old, new in delivery_map.items():
        Delivery.objects.filter(status=old).update(status=new)

    route_map = {
        "draft": "Черновик",
        "planned": "Запланирован",
        "in_progress": "Выполняется",
        "done": "Завершён",
        "Черновик": "Черновик",
        "Запланирован": "Запланирован",
        "Опубликован": "Опубликован",
        "Выполняется": "Выполняется",
        "Завершён": "Завершён",
    }
    for old, new in route_map.items():
        Route.objects.filter(status=old).update(status=new)

    stop_map = {
        "planned": "Запланирована",
        "in_progress": "В пути",
        "done": "Доставлено",
        "Черновик": "Черновик",
        "Подтверждена": "Подтверждена",
        "Запланирована": "Запланирована",
        "В пути": "В пути",
        "Доставлено": "Доставлено",
        "Не доставлено": "Не доставлено",
        "Перенесено": "Перенесено",
        "Отменено": "Отменено",
    }
    for old, new in stop_map.items():
        RouteStop.objects.filter(status=old).update(status=new)

    for delivery in Delivery.objects.filter(delivery_date__isnull=True, planned_at__isnull=False):
        delivery.delivery_date = delivery.planned_at.date()
        delivery.save(update_fields=["delivery_date"])




class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_courier_current_latitude_courier_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='route',
            name='max_duration_minutes',
            field=models.PositiveSmallIntegerField(default=720, verbose_name='Макс. длительность (мин)'),
        ),
        migrations.AddField(
            model_name='route',
            name='soft_limit_stops',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Мягкий лимит точек'),
        ),
        migrations.AddField(
            model_name='route',
            name='strict_mode',
            field=models.BooleanField(default=False, verbose_name='Строгий режим лимита точек'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='failure_reason',
            field=models.TextField(blank=True, verbose_name='Причина недоставки'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_of_delivery',
            field=models.FileField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='Документ доставки'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время загрузки документа'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_delivery_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestop',
            name='service_time_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Время обслуживания (мин)'),
        ),
        migrations.RunPython(migrate_logistics_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Свободен'), ('Занят', 'Занят'), ('В рейсе', 'В рейсе')], default='Свободен', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Не назначено', 'Не назначено'), ('Запланировано', 'Запланировано'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено'), ('Отменено', 'Отменено')], default='Не назначено', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Запланирован', 'Запланирован'), ('Опубликован', 'Опубликован'), ('Выполняется', 'Выполняется'), ('Завершён', 'Завершён')], default='Черновик', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Подтверждена', 'Подтверждена'), ('Запланирована', 'Запланирована'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено'), ('Не доставлено', 'Не доставлено'), ('Перенесено', 'Перенесено'), ('Отменено', 'Отменено')], default='Черновик', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=64, verbose_name='Роль')),
                ('object_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('field_name', models.CharField(blank=True, max_length=64, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудит',
                'verbose_name_plural': 'Аудит',
            },
        ),
    ]
