# Generated by Django 6.0.1 on 2026-02-12 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_delivery_delivery_date_route_max_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='proof_review_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_review_status',
            field=models.CharField(choices=[('Ожидает проверки', 'Ожидает проверки'), ('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], default='Ожидает проверки', max_length=32, verbose_name='Статус проверки документа'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='proof_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
