# Generated by Django 6.0.1 on 2026-02-13 08:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_order_statuses(apps, schema_editor):
    Order = apps.get_model("crm", "Order")
    status_map = {
        "draft": "Черновик",
        "confirmed": "На проверке",
        "in_progress": "В производстве",
        "shipped": "Отгружен",
        "delivered": "Отгружен",
        "cancelled": "Отменен",
        "Черновик": "Черновик",
        "На проверке": "На проверке",
        "Подтвержден производством": "Подтвержден производством",
        "В производстве": "В производстве",
        "Готов к отгрузке": "Готов к отгрузке",
        "Отгружен": "Отгружен",
        "Отменен": "Отменен",
    }
    for old, new in status_map.items():
        Order.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_routestop_proof_review_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Оборудование')),
                ('capacity_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Производительность/час')),
                ('available_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доступные часы')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='daily_max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. вес в день (кг)'),
        ),
        migrations.AddField(
            model_name='client',
            name='daily_min_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мин. объём заказа'),
        ),
        migrations.AddField(
            model_name='client',
            name='guaranteed_volume_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Гарантированный объём (кг)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='batch_multiple_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Кратность партии'),
        ),
        migrations.AddField(
            model_name='dish',
            name='min_batch_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Мин. партия'),
        ),
        migrations.AddField(
            model_name='dish',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес единицы (кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Регулярная', 'Регулярная'), ('Разовая', 'Разовая'), ('Срочная', 'Срочная')], default='Разовая', max_length=32, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_shift',
            field=models.CharField(blank=True, max_length=32, verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_window_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Окно производства (до)'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_window_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Окно производства (с)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('На проверке', 'На проверке'), ('Подтвержден производством', 'Подтвержден производством'), ('В производстве', 'В производстве'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Отгружен', 'Отгружен'), ('Отменен', 'Отменен')], default='Черновик', max_length=64, verbose_name='Статус'),
        ),
        migrations.RunPython(migrate_order_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часы')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='crm.order')),
            ],
            options={
                'verbose_name': 'Резерв оборудования',
                'verbose_name_plural': 'Резервы оборудования',
            },
        ),
        migrations.CreateModel(
            name='IngredientReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_reservations', to='crm.order')),
            ],
            options={
                'verbose_name': 'Резерв ингредиента',
                'verbose_name_plural': 'Резервы ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='crm.ingredient')),
            ],
            options={
                'verbose_name': 'Остаток ингредиента',
                'verbose_name_plural': 'Остатки ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='ProductionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Вес (кг)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reservations', to='crm.order')),
            ],
            options={
                'verbose_name': 'Резерв мощности производства',
                'verbose_name_plural': 'Резервы мощности производства',
            },
        ),
        migrations.CreateModel(
            name='ClientAllowedTechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_tech_cards', to='crm.client')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_for_clients', to='crm.techcard')),
            ],
            options={
                'verbose_name': 'Разрешённая техкарта клиента',
                'verbose_name_plural': 'Разрешённые техкарты клиентов',
                'unique_together': {('client', 'tech_card')},
            },
        ),
        migrations.CreateModel(
            name='DishEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минут на единицу')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='crm.dish')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_requirements', to='crm.equipment')),
            ],
            options={
                'verbose_name': 'Требование оборудования',
                'verbose_name_plural': 'Требования оборудования',
                'unique_together': {('dish', 'equipment')},
            },
        ),
    ]
