# Generated by Django 6.0.1 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_equipment_client_daily_max_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Базовая цена'),
        ),
    ]
