# Generated by Django 6.0.1 on 2026-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_dish_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='daily_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Суточная мощность'),
        ),
    ]
