# Generated by Django 6.0.1 on 2026-02-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_dish_daily_capacity'),
        ('crm', '0015_dish_uom_fields'),
    ]

    operations = [
    ]
